version: '3'
services:
  master-node:
    image: sg162/map_reduce:master_node
    ports:
      - "5000:5000"
    environment:
      - LOGGING_LEVEL=DEBUG
    networks:
      map-reduce-network:
        aliases:
          - master-node-alias

  worker-node-1:
    image: sg162/map_reduce:worker_node
    networks:
      - map-reduce-network
    depends_on:
    - master-node
    environment:
      - MASTER_HOST_IP=master-node-alias
      - WORKER_HOST_IP=0.0.0.0
      - LOGGING_LEVEL=DEBUG

  worker-node-2:
    image: sg162/map_reduce:worker_node
    networks:
      - map-reduce-network
    depends_on:
      - master-node
      - worker-node-1
    environment:
      - MASTER_HOST_IP=master-node-alias
      - WORKER_HOST_IP=0.0.0.0
      - LOGGING_LEVEL=DEBUG

  worker-node-3:
    image: sg162/map_reduce:worker_node
    networks:
      - map-reduce-network
    depends_on:
      - master-node
      - worker-node-1
      - worker-node-2
    environment:
      - MASTER_HOST_IP=master-node-alias
      - WORKER_HOST_IP=0.0.0.0
      - LOGGING_LEVEL=DEBUG

networks:
  map-reduce-network: {}